# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guigui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1622, 1024)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/all/icones/TeXamator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.big_splitter = QtWidgets.QSplitter(self.centralwidget)
        self.big_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.big_splitter.setHandleWidth(6)
        self.big_splitter.setObjectName("big_splitter")
        self.layoutWidget = QtWidgets.QWidget(self.big_splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.hboxlayout.setObjectName("hboxlayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.hboxlayout.addWidget(self.lineEdit)
        self.pushButton_parcourir = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_parcourir.sizePolicy().hasHeightForWidth())
        self.pushButton_parcourir.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/all/icones/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_parcourir.setIcon(icon1)
        self.pushButton_parcourir.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_parcourir.setObjectName("pushButton_parcourir")
        self.hboxlayout.addWidget(self.pushButton_parcourir)
        self.button_refresh = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_refresh.sizePolicy().hasHeightForWidth())
        self.button_refresh.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/all/icones/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_refresh.setIcon(icon2)
        self.button_refresh.setIconSize(QtCore.QSize(20, 20))
        self.button_refresh.setObjectName("button_refresh")
        self.hboxlayout.addWidget(self.button_refresh)
        self.verticalLayout_3.addLayout(self.hboxlayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.little_splitter = QtWidgets.QSplitter(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.little_splitter.sizePolicy().hasHeightForWidth())
        self.little_splitter.setSizePolicy(sizePolicy)
        self.little_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.little_splitter.setHandleWidth(6)
        self.little_splitter.setObjectName("little_splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.little_splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.layoutWidget1)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidget.setIndentation(10)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout.addWidget(self.treeWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_search = QtWidgets.QLabel(self.layoutWidget1)
        self.label_search.setObjectName("label_search")
        self.horizontalLayout.addWidget(self.label_search)
        self.lineEdit_search = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget2 = QtWidgets.QWidget(self.little_splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget2)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_edit = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_edit.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/all/icones/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_edit.setIcon(icon3)
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.horizontalLayout_2.addWidget(self.pushButton_edit)
        spacerItem = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_preview = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_preview.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/all/icones/pdf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_preview.setIcon(icon4)
        self.pushButton_preview.setObjectName("pushButton_preview")
        self.horizontalLayout_2.addWidget(self.pushButton_preview)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.button_remove = QtWidgets.QPushButton(self.layoutWidget2)
        self.button_remove.setEnabled(False)
        self.button_remove.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/all/icones/edit_remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_remove.setIcon(icon5)
        self.button_remove.setObjectName("button_remove")
        self.hboxlayout1.addWidget(self.button_remove)
        self.button_add = QtWidgets.QPushButton(self.layoutWidget2)
        self.button_add.setEnabled(False)
        self.button_add.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/all/icones/edit_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_add.setIcon(icon6)
        self.button_add.setObjectName("button_add")
        self.hboxlayout1.addWidget(self.button_add)
        spacerItem1 = QtWidgets.QSpacerItem(31, 21, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.button_up = QtWidgets.QPushButton(self.layoutWidget2)
        self.button_up.setEnabled(False)
        self.button_up.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/all/icones/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_up.setIcon(icon7)
        self.button_up.setObjectName("button_up")
        self.hboxlayout1.addWidget(self.button_up)
        self.button_down = QtWidgets.QPushButton(self.layoutWidget2)
        self.button_down.setEnabled(False)
        self.button_down.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/all/icones/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_down.setIcon(icon8)
        self.button_down.setObjectName("button_down")
        self.hboxlayout1.addWidget(self.button_down)
        self.verticalLayout_2.addLayout(self.hboxlayout1)
        self.verticalLayout_5.addWidget(self.little_splitter)
        self.layoutWidget3 = QtWidgets.QWidget(self.big_splitter)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pdfScrollArea = QtWidgets.QScrollArea(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdfScrollArea.sizePolicy().hasHeightForWidth())
        self.pdfScrollArea.setSizePolicy(sizePolicy)
        self.pdfScrollArea.setFrameShape(QtWidgets.QFrame.Panel)
        self.pdfScrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pdfScrollArea.setLineWidth(2)
        self.pdfScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.pdfScrollArea.setWidgetResizable(True)
        self.pdfScrollArea.setObjectName("pdfScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 681, 904))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pdfScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.pdfScrollArea)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_recompile = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_recompile.sizePolicy().hasHeightForWidth())
        self.button_recompile.setSizePolicy(sizePolicy)
        self.button_recompile.setObjectName("button_recompile")
        self.horizontalLayout_3.addWidget(self.button_recompile)
        spacerItem2 = QtWidgets.QSpacerItem(231, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.button_save = QtWidgets.QPushButton(self.layoutWidget3)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/all/icones/filesave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_save.setIcon(icon9)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout_3.addWidget(self.button_save)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.big_splitter, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1622, 43))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuEdition = QtWidgets.QMenu(self.menubar)
        self.menuEdition.setObjectName("menuEdition")
        self.menuChange_language = QtWidgets.QMenu(self.menuEdition)
        self.menuChange_language.setObjectName("menuChange_language")
        self.menuCompilation = QtWidgets.QMenu(self.menuEdition)
        self.menuCompilation.setObjectName("menuCompilation")
        self.menuPreamble = QtWidgets.QMenu(self.menuEdition)
        self.menuPreamble.setObjectName("menuPreamble")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menubar)
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setIcon(icon9)
        self.actionExport.setObjectName("actionExport")
        self.actionPartieliser = QtWidgets.QAction(MainWindow)
        self.actionPartieliser.setIcon(icon3)
        self.actionPartieliser.setObjectName("actionPartieliser")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/all/icones/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuitter.setIcon(icon10)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionPrefs = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/all/icones/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrefs.setIcon(icon11)
        self.actionPrefs.setObjectName("actionPrefs")
        self.actionA_propos = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/all/icones/messagebox_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionA_propos.setIcon(icon12)
        self.actionA_propos.setObjectName("actionA_propos")
        self.actionGenerate_Random_Exam = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/all/icones/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGenerate_Random_Exam.setIcon(icon13)
        self.actionGenerate_Random_Exam.setObjectName("actionGenerate_Random_Exam")
        self.actionEdit_exercise = QtWidgets.QAction(MainWindow)
        self.actionEdit_exercise.setEnabled(False)
        self.actionEdit_exercise.setIcon(icon3)
        self.actionEdit_exercise.setObjectName("actionEdit_exercise")
        self.actionExpand_Collapse = QtWidgets.QAction(MainWindow)
        self.actionExpand_Collapse.setEnabled(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/all/icones/2downarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExpand_Collapse.setIcon(icon14)
        self.actionExpand_Collapse.setObjectName("actionExpand_Collapse")
        self.actionStart_Wizard = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/all/icones/hat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart_Wizard.setIcon(icon15)
        self.actionStart_Wizard.setObjectName("actionStart_Wizard")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionFrench = QtWidgets.QAction(MainWindow)
        self.actionFrench.setObjectName("actionFrench")
        self.actionCzech = QtWidgets.QAction(MainWindow)
        self.actionCzech.setObjectName("actionCzech")
        self.actionUkrainian = QtWidgets.QAction(MainWindow)
        self.actionUkrainian.setObjectName("actionUkrainian")
        self.actionGerman = QtWidgets.QAction(MainWindow)
        self.actionGerman.setObjectName("actionGerman")
        self.actionM = QtWidgets.QAction(MainWindow)
        self.actionM.setObjectName("actionM")
        self.actionShuffle_list = QtWidgets.QAction(MainWindow)
        self.actionShuffle_list.setEnabled(False)
        self.actionShuffle_list.setObjectName("actionShuffle_list")
        self.actionA = QtWidgets.QAction(MainWindow)
        self.actionA.setObjectName("actionA")
        self.menuFichier.addAction(self.actionExport)
        self.menuFichier.addAction(self.actionGenerate_Random_Exam)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionQuitter)
        self.menuChange_language.addAction(self.actionCzech)
        self.menuChange_language.addAction(self.actionEnglish)
        self.menuChange_language.addAction(self.actionFrench)
        self.menuChange_language.addAction(self.actionGerman)
        self.menuChange_language.addAction(self.actionUkrainian)
        self.menuEdition.addAction(self.actionStart_Wizard)
        self.menuEdition.addAction(self.actionPrefs)
        self.menuEdition.addAction(self.menuCompilation.menuAction())
        self.menuEdition.addAction(self.menuPreamble.menuAction())
        self.menuEdition.addAction(self.actionEdit_exercise)
        self.menuEdition.addAction(self.actionExpand_Collapse)
        self.menuEdition.addAction(self.actionShuffle_list)
        self.menuEdition.addSeparator()
        self.menuEdition.addAction(self.menuChange_language.menuAction())
        self.menuAide.addAction(self.actionA_propos)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuEdition.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TeXamator"))
        self.label.setText(_translate("MainWindow", "Folder in which TeXamator should look for exercices"))
        self.pushButton_parcourir.setText(_translate("MainWindow", "Browse"))
        self.button_refresh.setText(_translate("MainWindow", "Look for exercices !"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Exercise list"))
        self.label_search.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Exercise"))
        self.pushButton_edit.setText(_translate("MainWindow", "Edit"))
        self.pushButton_preview.setText(_translate("MainWindow", "Preview"))
        self.button_recompile.setText(_translate("MainWindow", "Re-run LaTeX"))
        self.button_save.setText(_translate("MainWindow", "Export"))
        self.menuFichier.setTitle(_translate("MainWindow", "File"))
        self.menuEdition.setTitle(_translate("MainWindow", "Edit"))
        self.menuChange_language.setTitle(_translate("MainWindow", "Choose language"))
        self.menuCompilation.setTitle(_translate("MainWindow", "Compilation"))
        self.menuPreamble.setTitle(_translate("MainWindow", "Preamble"))
        self.menuAide.setTitle(_translate("MainWindow", "Help"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionPartieliser.setText(_translate("MainWindow", "Generate Exam"))
        self.actionQuitter.setText(_translate("MainWindow", "Quit"))
        self.actionPrefs.setText(_translate("MainWindow", "Preferences"))
        self.actionA_propos.setText(_translate("MainWindow", "About ..."))
        self.actionGenerate_Random_Exam.setText(_translate("MainWindow", "Pick exercises randomly"))
        self.actionEdit_exercise.setText(_translate("MainWindow", "Edit exercise"))
        self.actionExpand_Collapse.setText(_translate("MainWindow", "Expand/Collapse"))
        self.actionStart_Wizard.setText(_translate("MainWindow", "Start Wizard"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
        self.actionFrench.setText(_translate("MainWindow", "French"))
        self.actionCzech.setText(_translate("MainWindow", "Czech"))
        self.actionUkrainian.setText(_translate("MainWindow", "Ukrainian"))
        self.actionGerman.setText(_translate("MainWindow", "German"))
        self.actionM.setText(_translate("MainWindow", "m"))
        self.actionShuffle_list.setText(_translate("MainWindow", "Shuffle list"))
        self.actionA.setText(_translate("MainWindow", "a"))

from . import icones_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

