# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guigui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1622, 1024)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/TeXamator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.big_splitter = QtGui.QSplitter(self.centralwidget)
        self.big_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.big_splitter.setObjectName(_fromUtf8("big_splitter"))
        self.layoutWidget = QtGui.QWidget(self.big_splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.hboxlayout.addWidget(self.lineEdit)
        self.pushButton_parcourir = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_parcourir.sizePolicy().hasHeightForWidth())
        self.pushButton_parcourir.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_parcourir.setIcon(icon1)
        self.pushButton_parcourir.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_parcourir.setObjectName(_fromUtf8("pushButton_parcourir"))
        self.hboxlayout.addWidget(self.pushButton_parcourir)
        self.button_refresh = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_refresh.sizePolicy().hasHeightForWidth())
        self.button_refresh.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/find.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_refresh.setIcon(icon2)
        self.button_refresh.setIconSize(QtCore.QSize(20, 20))
        self.button_refresh.setObjectName(_fromUtf8("button_refresh"))
        self.hboxlayout.addWidget(self.button_refresh)
        self.verticalLayout_3.addLayout(self.hboxlayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.little_splitter = QtGui.QSplitter(self.layoutWidget)
        self.little_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.little_splitter.setObjectName(_fromUtf8("little_splitter"))
        self.layoutWidget1 = QtGui.QWidget(self.little_splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeWidget = QtGui.QTreeWidget(self.layoutWidget1)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeWidget.setIndentation(10)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.verticalLayout.addWidget(self.treeWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_search = QtGui.QLabel(self.layoutWidget1)
        self.label_search.setObjectName(_fromUtf8("label_search"))
        self.horizontalLayout.addWidget(self.label_search)
        self.lineEdit_search = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_search.setObjectName(_fromUtf8("lineEdit_search"))
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget2 = QtGui.QWidget(self.little_splitter)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.layoutWidget2)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_edit = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_edit.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_edit.setIcon(icon3)
        self.pushButton_edit.setObjectName(_fromUtf8("pushButton_edit"))
        self.horizontalLayout_2.addWidget(self.pushButton_edit)
        spacerItem = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_preview = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_preview.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/pdf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_preview.setIcon(icon4)
        self.pushButton_preview.setObjectName(_fromUtf8("pushButton_preview"))
        self.horizontalLayout_2.addWidget(self.pushButton_preview)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.button_remove = QtGui.QPushButton(self.layoutWidget2)
        self.button_remove.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/edit_remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_remove.setIcon(icon5)
        self.button_remove.setObjectName(_fromUtf8("button_remove"))
        self.hboxlayout1.addWidget(self.button_remove)
        self.button_add = QtGui.QPushButton(self.layoutWidget2)
        self.button_add.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/edit_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_add.setIcon(icon6)
        self.button_add.setObjectName(_fromUtf8("button_add"))
        self.hboxlayout1.addWidget(self.button_add)
        spacerItem1 = QtGui.QSpacerItem(31, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.button_up = QtGui.QPushButton(self.layoutWidget2)
        self.button_up.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_up.setIcon(icon7)
        self.button_up.setObjectName(_fromUtf8("button_up"))
        self.hboxlayout1.addWidget(self.button_up)
        self.button_down = QtGui.QPushButton(self.layoutWidget2)
        self.button_down.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_down.setIcon(icon8)
        self.button_down.setObjectName(_fromUtf8("button_down"))
        self.hboxlayout1.addWidget(self.button_down)
        self.verticalLayout_2.addLayout(self.hboxlayout1)
        self.verticalLayout_5.addWidget(self.little_splitter)
        self.layoutWidget3 = QtGui.QWidget(self.big_splitter)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.okularlayout = QtGui.QScrollArea(self.layoutWidget3)
        self.okularlayout.setSizeIncrement(QtCore.QSize(0, 0))
        self.okularlayout.setWidgetResizable(True)
        self.okularlayout.setObjectName(_fromUtf8("okularlayout"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 684, 864))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.okularlayout.setWidget(self.scrollAreaWidgetContents)
        self._2.addWidget(self.okularlayout)
        self.hboxlayout2.addLayout(self._2)
        self.verticalLayout_4.addLayout(self.hboxlayout2)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.button_recompile = QtGui.QPushButton(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_recompile.sizePolicy().hasHeightForWidth())
        self.button_recompile.setSizePolicy(sizePolicy)
        self.button_recompile.setObjectName(_fromUtf8("button_recompile"))
        self.horizontalLayout_3.addWidget(self.button_recompile)
        spacerItem2 = QtGui.QSpacerItem(231, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.button_save = QtGui.QPushButton(self.layoutWidget3)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_save.setIcon(icon9)
        self.button_save.setObjectName(_fromUtf8("button_save"))
        self.horizontalLayout_3.addWidget(self.button_save)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.big_splitter, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1622, 43))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menuEdition = QtGui.QMenu(self.menubar)
        self.menuEdition.setObjectName(_fromUtf8("menuEdition"))
        self.menuChange_language = QtGui.QMenu(self.menuEdition)
        self.menuChange_language.setObjectName(_fromUtf8("menuChange_language"))
        self.menuCompilation = QtGui.QMenu(self.menuEdition)
        self.menuCompilation.setObjectName(_fromUtf8("menuCompilation"))
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName(_fromUtf8("menuAide"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setIcon(icon9)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionPartieliser = QtGui.QAction(MainWindow)
        self.actionPartieliser.setIcon(icon3)
        self.actionPartieliser.setObjectName(_fromUtf8("actionPartieliser"))
        self.actionQuitter = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuitter.setIcon(icon10)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.actionPrefs = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/gear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrefs.setIcon(icon11)
        self.actionPrefs.setObjectName(_fromUtf8("actionPrefs"))
        self.actionA_propos = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/messagebox_info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionA_propos.setIcon(icon12)
        self.actionA_propos.setObjectName(_fromUtf8("actionA_propos"))
        self.actionGenerate_Random_Exam = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/pencil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGenerate_Random_Exam.setIcon(icon13)
        self.actionGenerate_Random_Exam.setObjectName(_fromUtf8("actionGenerate_Random_Exam"))
        self.actionEdit_exercise = QtGui.QAction(MainWindow)
        self.actionEdit_exercise.setEnabled(False)
        self.actionEdit_exercise.setIcon(icon3)
        self.actionEdit_exercise.setObjectName(_fromUtf8("actionEdit_exercise"))
        self.actionExpand_Collapse = QtGui.QAction(MainWindow)
        self.actionExpand_Collapse.setEnabled(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/2downarrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExpand_Collapse.setIcon(icon14)
        self.actionExpand_Collapse.setObjectName(_fromUtf8("actionExpand_Collapse"))
        self.actionStart_Wizard = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/all/icones/hat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart_Wizard.setIcon(icon15)
        self.actionStart_Wizard.setObjectName(_fromUtf8("actionStart_Wizard"))
        self.actionEnglish = QtGui.QAction(MainWindow)
        self.actionEnglish.setObjectName(_fromUtf8("actionEnglish"))
        self.actionFrench = QtGui.QAction(MainWindow)
        self.actionFrench.setObjectName(_fromUtf8("actionFrench"))
        self.actionCzech = QtGui.QAction(MainWindow)
        self.actionCzech.setObjectName(_fromUtf8("actionCzech"))
        self.actionUkrainian = QtGui.QAction(MainWindow)
        self.actionUkrainian.setObjectName(_fromUtf8("actionUkrainian"))
        self.actionGerman = QtGui.QAction(MainWindow)
        self.actionGerman.setObjectName(_fromUtf8("actionGerman"))
        self.actionM = QtGui.QAction(MainWindow)
        self.actionM.setObjectName(_fromUtf8("actionM"))
        self.menuFichier.addAction(self.actionExport)
        self.menuFichier.addAction(self.actionGenerate_Random_Exam)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionQuitter)
        self.menuChange_language.addAction(self.actionCzech)
        self.menuChange_language.addAction(self.actionEnglish)
        self.menuChange_language.addAction(self.actionFrench)
        self.menuChange_language.addAction(self.actionGerman)
        self.menuChange_language.addAction(self.actionUkrainian)
        self.menuEdition.addAction(self.actionStart_Wizard)
        self.menuEdition.addAction(self.actionPrefs)
        self.menuEdition.addAction(self.menuCompilation.menuAction())
        self.menuEdition.addAction(self.actionEdit_exercise)
        self.menuEdition.addAction(self.actionExpand_Collapse)
        self.menuEdition.addSeparator()
        self.menuEdition.addAction(self.menuChange_language.menuAction())
        self.menuAide.addAction(self.actionA_propos)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuEdition.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "TeXamator", None))
        self.label.setText(_translate("MainWindow", "Folder in which TeXamator should look for exercices", None))
        self.pushButton_parcourir.setText(_translate("MainWindow", "Browse", None))
        self.button_refresh.setText(_translate("MainWindow", "Look for exercices !", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "1", None))
        self.label_search.setText(_translate("MainWindow", "Search", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Exercises", None))
        self.pushButton_edit.setText(_translate("MainWindow", "Edit", None))
        self.pushButton_preview.setText(_translate("MainWindow", "Preview", None))
        self.button_recompile.setText(_translate("MainWindow", "Re-run LaTeX", None))
        self.button_save.setText(_translate("MainWindow", "Export", None))
        self.menuFichier.setTitle(_translate("MainWindow", "File", None))
        self.menuEdition.setTitle(_translate("MainWindow", "Edit", None))
        self.menuChange_language.setTitle(_translate("MainWindow", "Choose language", None))
        self.menuCompilation.setTitle(_translate("MainWindow", "Compilation", None))
        self.menuAide.setTitle(_translate("MainWindow", "Help", None))
        self.actionExport.setText(_translate("MainWindow", "Export", None))
        self.actionPartieliser.setText(_translate("MainWindow", "Generate Exam", None))
        self.actionQuitter.setText(_translate("MainWindow", "Quit", None))
        self.actionPrefs.setText(_translate("MainWindow", "Preferences", None))
        self.actionA_propos.setText(_translate("MainWindow", "About ...", None))
        self.actionGenerate_Random_Exam.setText(_translate("MainWindow", "Pick exercises randomly", None))
        self.actionEdit_exercise.setText(_translate("MainWindow", "Edit exercise", None))
        self.actionExpand_Collapse.setText(_translate("MainWindow", "Expand/Collapse", None))
        self.actionStart_Wizard.setText(_translate("MainWindow", "Start Wizard", None))
        self.actionEnglish.setText(_translate("MainWindow", "English", None))
        self.actionFrench.setText(_translate("MainWindow", "French", None))
        self.actionCzech.setText(_translate("MainWindow", "Czech", None))
        self.actionUkrainian.setText(_translate("MainWindow", "Ukrainian", None))
        self.actionGerman.setText(_translate("MainWindow", "German", None))
        self.actionM.setText(_translate("MainWindow", "m", None))

import icones_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

