# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(735, 983)
        Dialog.setMinimumSize(QtCore.QSize(600, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/all/icones/TeXamator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame1 = QtWidgets.QFrame(Dialog)
        self.frame1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(130, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame1)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/all/icones/wizard.png"))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_warning = QtWidgets.QLabel(self.frame1)
        self.label_warning.setWordWrap(True)
        self.label_warning.setObjectName("label_warning")
        self.verticalLayout_2.addWidget(self.label_warning)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(self.frame1)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.frame1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_browse = QtWidgets.QPushButton(self.frame1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/all/icones/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_browse.setIcon(icon1)
        self.pushButton_browse.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.horizontalLayout.addWidget(self.pushButton_browse)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_3.addWidget(self.frame1, 0, 0, 1, 1)
        self.frame2 = QtWidgets.QFrame(Dialog)
        self.frame2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_tags = QtWidgets.QLabel(self.frame2)
        self.label_tags.setWordWrap(True)
        self.label_tags.setObjectName("label_tags")
        self.gridLayout_4.addWidget(self.label_tags, 0, 0, 1, 1)
        self._2 = QtWidgets.QGridLayout()
        self._2.setObjectName("_2")
        self.label_5 = QtWidgets.QLabel(self.frame2)
        self.label_5.setObjectName("label_5")
        self._2.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_tag1 = QtWidgets.QLineEdit(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tag1.sizePolicy().hasHeightForWidth())
        self.lineEdit_tag1.setSizePolicy(sizePolicy)
        self.lineEdit_tag1.setObjectName("lineEdit_tag1")
        self._2.addWidget(self.lineEdit_tag1, 1, 0, 1, 1)
        self.lineEdit_tag2 = QtWidgets.QLineEdit(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tag2.sizePolicy().hasHeightForWidth())
        self.lineEdit_tag2.setSizePolicy(sizePolicy)
        self.lineEdit_tag2.setObjectName("lineEdit_tag2")
        self._2.addWidget(self.lineEdit_tag2, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame2)
        self.label_6.setObjectName("label_6")
        self._2.addWidget(self.label_6, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self._2, 1, 0, 1, 1)
        self._3 = QtWidgets.QHBoxLayout()
        self._3.setObjectName("_3")
        self.listWidget = QtWidgets.QListWidget(self.frame2)
        self.listWidget.setObjectName("listWidget")
        self._3.addWidget(self.listWidget)
        self._4 = QtWidgets.QVBoxLayout()
        self._4.setObjectName("_4")
        self.pushButton_add = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add.sizePolicy().hasHeightForWidth())
        self.pushButton_add.setSizePolicy(sizePolicy)
        self.pushButton_add.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/all/icones/edit_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add.setIcon(icon2)
        self.pushButton_add.setObjectName("pushButton_add")
        self._4.addWidget(self.pushButton_add)
        self.pushButton_remove = QtWidgets.QPushButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_remove.sizePolicy().hasHeightForWidth())
        self.pushButton_remove.setSizePolicy(sizePolicy)
        self.pushButton_remove.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/all/icones/edit_remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_remove.setIcon(icon3)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self._4.addWidget(self.pushButton_remove)
        spacerItem5 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self._4.addItem(spacerItem5)
        self._3.addLayout(self._4)
        self.gridLayout_4.addLayout(self._3, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame2, 1, 0, 1, 1)
        self.frame3 = QtWidgets.QFrame(Dialog)
        self.frame3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3.setObjectName("frame3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_header = QtWidgets.QLabel(self.frame3)
        self.label_header.setWordWrap(True)
        self.label_header.setObjectName("label_header")
        self.gridLayout_2.addWidget(self.label_header, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.frame3)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 2, 0, 1, 1)
        self.label_warning_2 = QtWidgets.QLabel(self.frame3)
        self.label_warning_2.setWordWrap(True)
        self.label_warning_2.setObjectName("label_warning_2")
        self.gridLayout_2.addWidget(self.label_warning_2, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame3, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_back = QtWidgets.QPushButton(Dialog)
        self.pushButton_back.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/all/icones/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_back.setIcon(icon4)
        self.pushButton_back.setObjectName("pushButton_back")
        self.gridLayout.addWidget(self.pushButton_back, 1, 2, 1, 1)
        self.pushButton_next = QtWidgets.QPushButton(Dialog)
        self.pushButton_next.setEnabled(False)
        self.pushButton_next.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/all/icones/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next.setIcon(icon5)
        self.pushButton_next.setObjectName("pushButton_next")
        self.gridLayout.addWidget(self.pushButton_next, 1, 3, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/all/icones/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cancel.setIcon(icon6)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 1, 0, 1, 1)
        self.pushButton_apply = QtWidgets.QPushButton(Dialog)
        self.pushButton_apply.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/all/icones/apply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_apply.setIcon(icon7)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.gridLayout.addWidget(self.pushButton_apply, 1, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.pushButton_cancel.clicked.connect(Dialog.reject)
        self.pushButton_apply.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Wizard"))
        self.label_warning.setText(_translate("Dialog", "Warning ! This wizard will erase some of your settings !"))
        self.label_3.setText(_translate("Dialog", "TeXamator needs to know a few things before it can fully work :\n"
"- how do you declare your exercises in your tex files ?\n"
"- what header do you use to compile your files (what comes before begin{document}) ?\n"
"\n"
"If you want, TeXamator can try to find out automatically. Just enter the location of one of your typical tex files with some exercices in it and hit the \"Next\" button."))
        self.pushButton_browse.setText(_translate("Dialog", "Browse"))
        self.label_tags.setText(_translate("Dialog", "Here are the tags TeXamator found. You can add or delete tags from the list."))
        self.label_5.setText(_translate("Dialog", "What comes before an exercise ?"))
        self.label_6.setText(_translate("Dialog", "What comes after ?"))
        self.label_header.setText(_translate("Dialog", "Here is the header TeXamator is going to use each time it needs to compile a file."))
        self.label_warning_2.setText(_translate("Dialog", "Note that \\begin{document} must not appear here !"))
        self.pushButton_back.setText(_translate("Dialog", "Back"))
        self.pushButton_next.setText(_translate("Dialog", "Next"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))
        self.pushButton_apply.setText(_translate("Dialog", "Apply"))

from . import icones_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

